#!/usr/bin/env bash
set -euo pipefail

# Undo what install.sh / setup-*.sh put on this machine.
#
# Usage: ./cleanup.sh [-f] [-a]
#   -f  skip the foreign-checkout guard
#   -a  also remove language toolchains installed by setup-*.sh
#       (sdkman, quicklisp, uv). ~/go is never touched — it may hold code.
#
# System packages are never uninstalled (shared dependencies); the list to
# remove by hand is printed at the end.

FORCE=0
ALL=0
while getopts ":fa" opt; do
    case "$opt" in
        f)  FORCE=1 ;;
        a)  ALL=1 ;;
        \?) echo "Usage: $0 [-f] [-a]" >&2; exit 2 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SELF_DIR="$(cd "$SCRIPT_DIR" && pwd -P)"

# The package table, so the summary at the end names what install.sh installs
# today rather than a list that drifts.
source "$SCRIPT_DIR/lib/pkg.sh"

# Same guard as install.sh: if a different checkout owns this home, nothing
# here was installed by this repository, and removing fonts or config would break that setup.
OTHER_DIR="$(cd "$HOME/.dotfiles" 2>/dev/null && pwd -P || true)"
if [ -n "$OTHER_DIR" ] && [ "$OTHER_DIR" != "$SELF_DIR" ] && [ "$FORCE" -ne 1 ]; then
    echo "A different dotfiles checkout owns this home ($OTHER_DIR) — refusing." >&2
    echo "Run with -f to force." >&2
    exit 1
fi

echo "This removes dotfiles symlinks, generated config, fonts$( [ "$ALL" -eq 1 ] && echo ', and language toolchains (sdkman, quicklisp, uv)')."
read -r -p "Proceed? [y/N] " answer
[[ "$answer" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }

removed=0

# Remove a path only if it is a symlink resolving into this repo
__rm_if_ours() {
    local dest=$1
    if [ -L "$dest" ] && [[ "$(readlink "$dest")" == "$SELF_DIR"/* ]]; then
        rm "$dest"
        removed=$((removed + 1))
    fi
}

# GNOME desktop settings — put the saved pre-dotfiles values back
if command -v gsettings >/dev/null 2>&1; then
    echo "Restoring GNOME settings..."
    python3 "$SCRIPT_DIR/bin/gnome-settings" restore || true
fi

# GNOME Shell extension installed by install.sh
QUAKE_UUID="quake-terminal@diegodario88.github.io"
if command -v gnome-extensions >/dev/null 2>&1 \
   && gnome-extensions list 2>/dev/null | grep -qx "$QUAKE_UUID"; then
    echo "Removing the Quake Terminal GNOME extension..."
    gnome-extensions uninstall "$QUAKE_UUID" >/dev/null 2>&1 || true
    removed=$((removed + 1))
fi

# systemd user units — disable ours while the unit files still exist, and undo
# the SSH-agent handover install.sh set up
if command -v systemctl >/dev/null 2>&1 && [ -d "/run/user/$(id -u)" ]; then
    echo "Disabling systemd user units..."
    UNIT_SRC_DIR="$SCRIPT_DIR/dotfiles/.config/systemd/user"
    for unit_path in "$UNIT_SRC_DIR"/*.service "$UNIT_SRC_DIR"/*.timer "$UNIT_SRC_DIR"/*.socket; do
        [ -e "$unit_path" ] || continue
        grep -q '^\[Install\]' "$unit_path" || continue
        systemctl --user disable --now "$(basename "$unit_path")" >/dev/null 2>&1 || true
    done

    systemctl --user disable --now gpg-agent-ssh.socket >/dev/null 2>&1 || true
    for unit in gcr-ssh-agent.socket gcr-ssh-agent.service gnome-keyring-ssh.service; do
        if [ "$(systemctl --user is-enabled "$unit" 2>/dev/null)" = "masked" ]; then
            echo "  -> Unmasking $unit"
            systemctl --user unmask "$unit" >/dev/null 2>&1 || true
        fi
    done
    systemctl --user daemon-reload >/dev/null 2>&1 || true
fi

echo "Removing symlinks into $SELF_DIR..."
while IFS= read -r -d '' src; do
    __rm_if_ours "$HOME/${src#"$SCRIPT_DIR/dotfiles/"}"
done < <(find "$SCRIPT_DIR/dotfiles" -type f -print0)

for src in "$SCRIPT_DIR"/bin/*; do
    [ -e "$src" ] && __rm_if_ours "$HOME/bin/$(basename "$src")"
done

echo "Removing managed ~/.bashrc.d files..."
if [ -d "$HOME/.bashrc.d" ]; then
    for rc in "$HOME/.bashrc.d"/*; do
        if [ -f "$rc" ] && grep -q '^# managed-by-dotfiles' "$rc"; then
            rm "$rc"
            removed=$((removed + 1))
        fi
    done
fi

echo "Removing 0xProto fonts..."
if [[ "$OSTYPE" == darwin* ]]; then FONT_DIR="$HOME/Library/Fonts"; else FONT_DIR="$HOME/.local/share/fonts"; fi
for f in "$SCRIPT_DIR"/general/0xProto/*.ttf; do
    dest="$FONT_DIR/$(basename "$f")"
    [ -f "$dest" ] && rm "$dest" && removed=$((removed + 1))
done
[[ "$OSTYPE" != darwin* ]] && command -v fc-cache >/dev/null 2>&1 && fc-cache -f "$FONT_DIR" || true

# Generated (non-symlink) config
if [ -f "$HOME/.config/ghostty/config.local" ]; then
    rm "$HOME/.config/ghostty/config.local"
    removed=$((removed + 1))
fi
if [ -f "$HOME/.gnupg/gpg-agent.conf" ] && grep -q 'Generated by dotfiles/install' "$HOME/.gnupg/gpg-agent.conf"; then
    rm "$HOME/.gnupg/gpg-agent.conf"
    removed=$((removed + 1))
    command -v gpg-connect-agent >/dev/null 2>&1 && gpg-connect-agent reloadagent /bye >/dev/null 2>&1 || true
fi

# Unset global git config keys, but only if they still hold the values install.sh sets
__git_unset_if() {
    local key=$1 expect=$2
    if [ "$(git config --global --get "$key" 2>/dev/null)" = "$expect" ]; then
        git config --global --unset "$key"
        removed=$((removed + 1))
    fi
}
if command -v git >/dev/null 2>&1; then
    echo "Unsetting global git config set by install.sh..."
    __git_unset_if user.name "Ishmael Aqsar"
    __git_unset_if user.email "ishmael-dev@aqsar.dev"
    __git_unset_if core.excludesfile "$HOME/.gitignore_global"
    __git_unset_if core.attributesfile "$HOME/.gitattributes"
    # The delta wiring. Leaving core.pager behind would break `git diff` on a
    # machine where the package is later removed.
    __git_unset_if core.pager "delta"
    __git_unset_if interactive.diffFilter "delta --color-only"
    __git_unset_if delta.navigate "true"
    # The path varies by distro, so match on the helper name
    case "$(git config --global --get credential.helper 2>/dev/null)" in
        */git-credential-libsecret)
            git config --global --unset credential.helper
            removed=$((removed + 1))
            ;;
    esac
fi

if [ "$ALL" -eq 1 ]; then
    echo "Removing language toolchains..."
    rm -rf "$HOME/.sdkman" "$HOME/quicklisp" "$HOME/.local/share/uv"
    rm -f "$HOME/.local/bin/uv" "$HOME/.local/bin/uvx"
    # uv tool shims are symlinks into ~/.local/share/uv, and the line above
    # left them dangling. Match on the target: deleting every dangling link in
    # ~/.local/bin would take the ones other tools own as well.
    for shim in "$HOME/.local/bin"/*; do
        [ -L "$shim" ] || continue
        case "$(readlink "$shim")" in
            *"/.local/share/uv/"*) rm -f "$shim" ;;
        esac
    done
    echo "Note: ~/go left alone (may contain your code) — remove gopls/dlv from ~/go/bin yourself."
    echo "Note: ~/.sbclrc may still reference quicklisp — edit it if you kept SBCL."
fi

echo
echo "Done: $removed item(s) removed."
echo "System packages are not uninstalled. Installed by these scripts (remove manually if wanted):"
# Every row that install.sh can select on some machine, by its first name.
TABLE_TOOLS="$(while IFS= read -r commands; do printf '%s ' "$(__pkg_primary "$commands")"; done < <(__pkg_select base linux desktop arch))"
echo "  install.sh:    ${TABLE_TOOLS}opencode ghostty, and yay on Arch"
echo "  System units left enabled (disable by hand): pcscd.socket, paccache.timer"
echo "  setup-c.sh:    build-essential/base-devel gdb lldb clangd cmake valgrind"
echo "  setup-go.sh:   go"
echo "  setup-sbcl.sh: sbcl"
