#!/usr/bin/env bash
set -euo pipefail

# Undo what install.sh / setup-*.sh put on this machine.
#
# Usage: ./cleanup.sh [-f] [-a]
#   -f  skip the foreign-checkout guard
#   -a  also remove language toolchains installed by setup-*.sh
#       (sdkman, quicklisp, uv). ~/go is never touched — it may hold code.
#
# System packages are never uninstalled (shared dependencies); the list to
# remove by hand is printed at the end.

FORCE=0
ALL=0
while getopts ":fa" opt; do
    case "$opt" in
        f)  FORCE=1 ;;
        a)  ALL=1 ;;
        \?) echo "Usage: $0 [-f] [-a]" >&2; exit 2 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SELF_DIR="$(cd "$SCRIPT_DIR" && pwd -P)"

# Same guard as install.sh: if a different checkout owns this home, nothing
# here was installed by us — removing fonts/config would break that setup.
OTHER_DIR="$(cd "$HOME/.dotfiles" 2>/dev/null && pwd -P || true)"
if [ -n "$OTHER_DIR" ] && [ "$OTHER_DIR" != "$SELF_DIR" ] && [ "$FORCE" -ne 1 ]; then
    echo "A different dotfiles checkout owns this home ($OTHER_DIR) — refusing." >&2
    echo "Run with -f to force." >&2
    exit 1
fi

echo "This removes dotfiles symlinks, generated config, fonts$( [ "$ALL" -eq 1 ] && echo ', and language toolchains (sdkman, quicklisp, uv)')."
read -r -p "Proceed? [y/N] " answer
[[ "$answer" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }

removed=0

# Remove a path only if it is a symlink resolving into this repo
__rm_if_ours() {
    local dest=$1
    if [ -L "$dest" ] && [[ "$(readlink "$dest")" == "$SELF_DIR"/* ]]; then
        rm "$dest"
        removed=$((removed + 1))
    fi
}

echo "Removing symlinks into $SELF_DIR..."
while IFS= read -r -d '' src; do
    __rm_if_ours "$HOME/${src#"$SCRIPT_DIR/dotfiles/"}"
done < <(find "$SCRIPT_DIR/dotfiles" -type f -print0)

for src in "$SCRIPT_DIR"/bin/*; do
    [ -e "$src" ] && __rm_if_ours "$HOME/bin/$(basename "$src")"
done

echo "Removing managed ~/.bashrc.d files..."
if [ -d "$HOME/.bashrc.d" ]; then
    for rc in "$HOME/.bashrc.d"/*; do
        if [ -f "$rc" ] && grep -q '^# managed-by-dotfiles' "$rc"; then
            rm "$rc"
            removed=$((removed + 1))
        fi
    done
fi

echo "Removing 0xProto fonts..."
if [[ "$OSTYPE" == darwin* ]]; then FONT_DIR="$HOME/Library/Fonts"; else FONT_DIR="$HOME/.local/share/fonts"; fi
for f in "$SCRIPT_DIR"/general/0xProto/*.ttf; do
    dest="$FONT_DIR/$(basename "$f")"
    [ -f "$dest" ] && rm "$dest" && removed=$((removed + 1))
done
[[ "$OSTYPE" != darwin* ]] && command -v fc-cache >/dev/null 2>&1 && fc-cache -f "$FONT_DIR" || true

# Generated (non-symlink) config
if [ -f "$HOME/.config/ghostty/config.local" ]; then
    rm "$HOME/.config/ghostty/config.local"
    removed=$((removed + 1))
fi
if [ -f "$HOME/.gnupg/gpg-agent.conf" ] && grep -q 'Generated by dotfiles/install' "$HOME/.gnupg/gpg-agent.conf"; then
    rm "$HOME/.gnupg/gpg-agent.conf"
    removed=$((removed + 1))
    command -v gpg-connect-agent >/dev/null 2>&1 && gpg-connect-agent reloadagent /bye >/dev/null 2>&1 || true
fi

# Unset global git config keys, but only if they still hold our values
__git_unset_if() {
    local key=$1 expect=$2
    if [ "$(git config --global --get "$key" 2>/dev/null)" = "$expect" ]; then
        git config --global --unset "$key"
        removed=$((removed + 1))
    fi
}
if command -v git >/dev/null 2>&1; then
    echo "Unsetting global git config set by install.sh..."
    __git_unset_if user.name "Ishmael Aqsar"
    __git_unset_if user.email "ishmael-dev@aqsar.dev"
    __git_unset_if core.excludesfile "$HOME/.gitignore_global"
    __git_unset_if core.attributesfile "$HOME/.gitattributes"
fi

if [ "$ALL" -eq 1 ]; then
    echo "Removing language toolchains..."
    rm -rf "$HOME/.sdkman" "$HOME/quicklisp" "$HOME/.local/share/uv"
    rm -f "$HOME/.local/bin/uv" "$HOME/.local/bin/uvx"
    # uv tool shims are symlinks into ~/.local/share/uv — now dangling
    find "$HOME/.local/bin" -maxdepth 1 -type l ! -exec test -e {} \; -delete 2>/dev/null || true
    echo "Note: ~/go left alone (may contain your code) — remove gopls/dlv from ~/go/bin yourself."
    echo "Note: ~/.sbclrc may still reference quicklisp — edit it if you kept SBCL."
fi

echo
echo "Done: $removed item(s) removed."
echo "System packages are not uninstalled. Installed by these scripts (remove manually if wanted):"
echo "  install.sh:    eza fd/fdfind ripgrep fzf git-delta zellij bash-completion gnupg pinentry opencode ghostty"
echo "  setup-c.sh:    build-essential/base-devel gdb lldb clangd cmake valgrind"
echo "  setup-go.sh:   go"
echo "  setup-sbcl.sh: sbcl"
