#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Personal dotfiles installer — macOS, Debian, Arch (GNOME), Fedora.
#
# Usage: ./install.sh [-f] [-n] [-c] [-y] [--desktop|--no-desktop] [target-dir]
#
# A non-$HOME target is a probe run: file layout only, all live-state steps
# (git --global, GPG keyring/agent, packages) are skipped.
#
# In a terminal the script asks before each optional group (packages, the
# desktop steps, OpenCode, Ghostty). With no terminal on stdin, or with -y,
# the detection decides and nothing asks.
# =============================================================================

# -----------------------------
# Options & target directory
# -----------------------------
FORCE=0
DRY_RUN=0
CHECK=0
ASSUME_YES=0
DESKTOP_OVERRIDE=""
TARGET_ARG=""

__usage() {
    cat <<'EOF'
Usage: ./install.sh [-f] [-n] [-c] [-y] [--desktop|--no-desktop] [target-dir]

  -f              install even when another dotfiles checkout owns ~/.dotfiles
  -n, --dry-run   print every change without making one
  -c, --check     report what is missing or has drifted, then exit
  -y, --yes       ask nothing; let the detection decide every optional step
  --desktop       run the desktop steps (GNOME settings, clipboard) regardless
  --no-desktop    skip them, whatever the session looks like
  -h, --help      show this text

A non-$HOME target is a probe run: file layout only, no live-state steps.
In a terminal the script asks before each optional group. Without one it
behaves as if -y was given.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        -f)            FORCE=1 ;;
        -n|--dry-run)  DRY_RUN=1 ;;
        -c|--check)    CHECK=1 ;;
        -y|--yes)      ASSUME_YES=1 ;;
        --desktop)     DESKTOP_OVERRIDE=1 ;;
        --no-desktop)  DESKTOP_OVERRIDE=0 ;;
        -h|--help)     __usage; exit 0 ;;
        -*)            echo "Unknown option: $1" >&2; __usage >&2; exit 2 ;;
        *)             TARGET_ARG="$1" ;;
    esac
    shift
done

# --check reads the machine and changes nothing, so it beats --dry-run.
if [ "$CHECK" -eq 1 ]; then
    DRY_RUN=0
fi

# python3 runs the symlink sync, the GNOME settings and the secrets hook. On a
# fresh macOS box /usr/bin/python3 is a stub that only prompts for the Xcode
# Command Line Tools, so test that it runs rather than that it exists.
if ! python3 -c '' >/dev/null 2>&1; then
    echo "Error: no working python3 — install.sh needs it for lib/sync-dotfiles." >&2
    if [[ "$OSTYPE" == darwin* ]]; then
        echo "Run 'xcode-select --install', then try again." >&2
    else
        echo "Install your distro's python3 package, then try again." >&2
    fi
    exit 1
fi

# Exported, so the shared helpers in lib/pkg.sh plan instead of installing.
export DOTFILES_DRY_RUN="$DRY_RUN"
if [ "$DRY_RUN" -eq 1 ]; then
    echo "=== Dry run: nothing on this machine changes. ==="
fi

TARGET_DIR="${TARGET_ARG:-$HOME}"
TARGET_DIR="${TARGET_DIR%/}"           # normalise trailing slash so the $HOME test holds
[ -z "$TARGET_DIR" ] && TARGET_DIR="/"

# Live-state steps run only for a real home install
IS_HOME_INSTALL=0
[ "$TARGET_DIR" = "$HOME" ] && IS_HOME_INSTALL=1

# Dev containers get symlinks and config only — no packages, fonts, or apps.
# DOTFILES_FORCE_HOST=1 disables the detection (container-based testing).
IN_CONTAINER=0
if [ -z "${DOTFILES_FORCE_HOST:-}" ]; then
    if [ -n "${REMOTE_CONTAINERS:-}" ] || [ -n "${CONTAINER_ID:-}" ] || [ -n "${CODESPACES:-}" ] || [ -f /.dockerenv ]; then
        IN_CONTAINER=1
    fi
fi

# Desktop box or headless? Gates desktop-only packages and GNOME settings, so
# a server or a container does not pull in a clipboard tool it cannot use.
IS_GRAPHICAL=0
if [ -n "${WAYLAND_DISPLAY:-}" ] || [ -n "${DISPLAY:-}" ] || command -v gnome-shell >/dev/null 2>&1; then
    IS_GRAPHICAL=1
fi
# --desktop / --no-desktop beat the detection. Needed for an install over ssh
# into a desktop box (no DISPLAY), and for a server that happens to have X libs.
if [ -n "$DESKTOP_OVERRIDE" ]; then
    IS_GRAPHICAL="$DESKTOP_OVERRIDE"
fi

# -----------------------------
# Absolute path to this script
# -----------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_BIN_DIR="$SCRIPT_DIR/bin"
DOTFILES_DIR="$SCRIPT_DIR/dotfiles"

# -----------------------------
# What a finished install looks like
# -----------------------------
# The global git keys. --check tests them, the steps below write them, and
# cleanup.sh unsets them, all from this one list.
source "$SCRIPT_DIR/lib/gitconfig.sh"

TARGET_BIN_DIR="$TARGET_DIR/bin"
GNUPG_DIR="$TARGET_DIR/.gnupg"
AGENT_CONF="$GNUPG_DIR/gpg-agent.conf"
AGENT_CONF_MARKER="Generated by dotfiles/install"

if [[ "$OSTYPE" == darwin* ]]; then
    FONT_DIR="$TARGET_DIR/Library/Fonts"
else
    FONT_DIR="$TARGET_DIR/.local/share/fonts"
fi

# The optional groups. The detection sets them, and the questions below can
# turn each one off. Everything else — the symlinks, the git config, the GPG
# agent — always runs, because without it the machine is not installed.
WANT_PACKAGES=1
WANT_HYPRLAND=0
command -v Hyprland >/dev/null 2>&1 && WANT_HYPRLAND=1
WANT_OPENCODE=1
WANT_GHOSTTY=1

# Ask before an optional group when a person is at the keyboard. A pipe, the
# dev-container hook, or an agent shell has no terminal on stdin, and a
# question there would hang, so those runs take the detection as it stands.
# -y does the same in a terminal. The modes that change nothing never ask.
INTERACTIVE=0
if [ "$ASSUME_YES" -eq 0 ] && [ "$DRY_RUN" -eq 0 ] && [ "$CHECK" -eq 0 ] && [ "$IS_HOME_INSTALL" -eq 1 ]; then
    if [ -t 0 ]; then
        INTERACTIVE=1
    else
        echo "No terminal on stdin — installing without questions, as with -y."
    fi
fi

# __ask "question" — 0 for yes. Enter is yes. Always yes when not interactive.
__ask() {
    local answer
    [ "$INTERACTIVE" -eq 1 ] || return 0
    read -r -p "$1 [Y/n] " answer
    [[ ! "$answer" =~ ^[Nn] ]]
}

# Which rows of lib/packages.conf apply to this machine. A row installs when
# all of its tags are active. Computed after the questions, because a "no"
# removes a tag.
__active_tags() {
    ACTIVE_TAGS=(base)
    [[ "$OSTYPE" != darwin* ]] && ACTIVE_TAGS+=(linux)
    [ "$IS_GRAPHICAL" -eq 1 ] && ACTIVE_TAGS+=(desktop)
    command -v pacman >/dev/null 2>&1 && ACTIVE_TAGS+=(arch)
    [ "$WANT_HYPRLAND" -eq 1 ] && ACTIVE_TAGS+=(hyprland)
    return 0
}
__active_tags

# Not every entry in bin/ is a script to link. Python writes its byte-code
# cache next to the scripts it runs, and a cache directory in ~/bin is junk.
# Both the link step and --check skip the same entries.
__skip_bin_entry() {
    case "$(basename "$1")" in
        __pycache__|*.pyc) return 0 ;;
    esac
    return 1
}

# -----------------------------
# Guard: refuse to install over a different dotfiles checkout
# -----------------------------
EXISTING_DOTFILES="$HOME/.dotfiles"
SELF_DIR="$(cd "$SCRIPT_DIR" && pwd -P)"
OTHER_DIR="$(cd "$EXISTING_DOTFILES" 2>/dev/null && pwd -P || true)"

if [ "$IS_HOME_INSTALL" -eq 1 ] \
   && [ -n "$OTHER_DIR" ] \
   && [ "$OTHER_DIR" != "$SELF_DIR" ] \
   && [ "$FORCE" -ne 1 ]; then
    # A dry run and a check change nothing, and a machine owned by another
    # checkout is exactly where reading the plan first is worth the most.
    if [ "$DRY_RUN" -eq 1 ] || [ "$CHECK" -eq 1 ]; then
        echo "Note: $EXISTING_DOTFILES belongs to another checkout. A real run would refuse; -f overrides."
    else
        echo "Dotfiles already present at $EXISTING_DOTFILES — refusing to install." >&2
        echo "Run with -f to force." >&2
        exit 1
    fi
fi

# -----------------------------
# Package installation
# -----------------------------
source "$SCRIPT_DIR/lib/pkg.sh"
PKG_MGR="$(__detect_pkg_mgr)"

# -----------------------------
# Check mode  (reads the machine, changes nothing)
# -----------------------------
# Answers "is this machine still correctly installed?" without a real run.
# A missing or drifted file is a failure, because install.sh always writes it.
# A missing package is only a warning: packages are best-effort, and install.sh
# itself warns and continues when one has no package on this platform.
CHECK_FAILURES=0
__check_fail() {
    echo "  FAIL: $*"
    CHECK_FAILURES=$((CHECK_FAILURES + 1))
}

__check_install() {
    local script_path name dest font missing commands primary state before key value

    echo "Checking the install in $TARGET_DIR (nothing is changed)."

    echo "Symlinked dotfiles:"
    python3 "$SCRIPT_DIR/lib/sync-dotfiles" --check "$TARGET_DIR" \
        || __check_fail "the dotfiles tree does not match the repo — re-run install.sh"

    echo "Scripts in $TARGET_BIN_DIR:"
    missing=0
    for script_path in "$SOURCE_BIN_DIR"/*; do
        [ -e "$script_path" ] || continue
        __skip_bin_entry "$script_path" && continue
        name="$(basename "$script_path")"
        dest="$TARGET_BIN_DIR/$name"
        if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$script_path" ]; then
            continue
        fi
        __check_fail "$dest does not link to $script_path"
        missing=$((missing + 1))
    done
    [ "$missing" -eq 0 ] && echo "  ok: every bin/ script is linked"

    echo "Fonts in $FONT_DIR:"
    missing=0
    for font in "$SCRIPT_DIR"/general/0xProto/*.ttf; do
        [ -f "$FONT_DIR/$(basename "$font")" ] || missing=$((missing + 1))
    done
    if [ "$missing" -gt 0 ]; then
        __check_fail "$missing 0xProto font file(s) missing"
    else
        echo "  ok: the 0xProto family is installed"
    fi

    echo "Generated config:"
    if grep -q "$AGENT_CONF_MARKER" "$AGENT_CONF" 2>/dev/null; then
        echo "  ok: $AGENT_CONF"
    else
        __check_fail "$AGENT_CONF is missing, or install.sh did not write it"
    fi

    echo "Packages for tags: ${ACTIVE_TAGS[*]}"
    while IFS= read -r commands; do
        state=0
        __pkg_present "$commands" || state=$?
        # 2 means no command answers to the row, so PATH proves nothing
        case "$state" in 0|2) continue ;; esac
        primary="$(__pkg_primary "$commands")"
        __warn "$primary not on PATH (package $(__pkg_name "$PKG_MGR" "$primary"))."
    done < <(__pkg_select "${ACTIVE_TAGS[@]}")
    command -v starship >/dev/null 2>&1 || __warn "starship not on PATH."

    # Live state, so a probe run cannot judge it
    if [ "$IS_HOME_INSTALL" -eq 0 ]; then
        echo "[probe] Skipping the global git config check."
    elif command -v git >/dev/null 2>&1; then
        echo "Global git config:"
        before="$CHECK_FAILURES"
        while IFS='=' read -r key value; do
            [ "$(git config --global --get "$key" 2>/dev/null)" = "$value" ] \
                || __check_fail "git $key is not '$value'"
        done <<< "$GIT_BASE_CONFIG"
        [ "$CHECK_FAILURES" -eq "$before" ] && echo "  ok: identity and ignore files set"

        # Only when delta is installed: without it, install.sh leaves the
        # default pager alone on purpose.
        if command -v delta >/dev/null 2>&1; then
            before="$CHECK_FAILURES"
            while IFS='=' read -r key value; do
                [ "$(git config --global --get "$key" 2>/dev/null)" = "$value" ] \
                    || __check_fail "git $key is not '$value'"
            done <<< "$GIT_DELTA_CONFIG"
            [ "$CHECK_FAILURES" -eq "$before" ] && echo "  ok: delta is the diff pager"
        fi
    fi

    echo
    if [ "$CHECK_FAILURES" -eq 0 ]; then
        echo "Check passed."
    else
        echo "$CHECK_FAILURES check(s) failed. Run ./install.sh to repair."
    fi
    if [ "$WARNING_COUNT" -gt 0 ]; then
        echo
        echo "$WARNING_COUNT package(s) need attention:"
        printf '%s' "$WARNING_LIST"
    fi

    [ "$CHECK_FAILURES" -eq 0 ]
}

if [ "$CHECK" -eq 1 ]; then
    __check_install
    exit $?
fi

# -----------------------------
# The questions  (a terminal, a home install, and no -y)
# -----------------------------
# One question per optional group, and only when the group applies to this
# machine. Each answer sets the variable that the step below already tests.
if [ "$INTERACTIVE" -eq 1 ]; then
    echo "Optional steps for this machine. Enter keeps the default."
    if [ "$IN_CONTAINER" -eq 0 ] && [ "$PKG_MGR" != "none" ]; then
        __ask "Install the packages via $PKG_MGR (tags: ${ACTIVE_TAGS[*]})?" || WANT_PACKAGES=0
    fi
    if [ "$IS_GRAPHICAL" -eq 1 ] && [[ "$OSTYPE" != darwin* ]]; then
        __ask "Desktop steps: the clipboard package, the GNOME settings and keys, the Quake Terminal extension?" \
            || IS_GRAPHICAL=0
    fi
    if [ "$WANT_HYPRLAND" -eq 1 ]; then
        __ask "Hyprland is installed. Install its session helpers (fuzzel, waybar, mako, hyprlock, grim, slurp, portal)?" \
            || WANT_HYPRLAND=0
    fi
    if [ "$IN_CONTAINER" -eq 0 ] && ! command -v opencode >/dev/null 2>&1; then
        __ask "Install OpenCode, the terminal agent?" || WANT_OPENCODE=0
    fi
    if [ "$IN_CONTAINER" -eq 0 ] && ! command -v ghostty >/dev/null 2>&1; then
        __ask "Install Ghostty, the terminal emulator?" || WANT_GHOSTTY=0
    fi
    __active_tags
    echo
fi

# Arch with no AUR helper: build one, then detect again so the rest of the run
# (and setup-java.sh's jdtls) can reach the AUR.
if [ "$PKG_MGR" = "pacman" ] && [ "$IS_HOME_INSTALL" -eq 1 ] && [ "$IN_CONTAINER" -eq 0 ] && [ "$WANT_PACKAGES" -eq 1 ]; then
    if __bootstrap_aur_helper; then
        PKG_MGR="$(__detect_pkg_mgr)"
    else
        __warn "no AUR helper — AUR-only packages are skipped."
    fi
fi

if [ "$IN_CONTAINER" -eq 1 ]; then
    echo "[container] Skipping package installation."
elif [ "$WANT_PACKAGES" -eq 0 ]; then
    echo "Skipping package installation, as asked."
elif [ "$IS_HOME_INSTALL" -eq 1 ] && [ "$PKG_MGR" != "none" ]; then
    echo "Installing packages via $PKG_MGR (tags: ${ACTIVE_TAGS[*]})..."
    __pkg_refresh "$PKG_MGR"

    # The list itself lives in lib/packages.conf, selected by tag.
    __pkg_install_tagged "$PKG_MGR" "${ACTIVE_TAGS[@]}"

    # The system units those packages bring, which a package install alone
    # does not start.
    if [[ "$OSTYPE" != darwin* ]] && command -v systemctl >/dev/null 2>&1; then
        # pcscd is socket-activated. Without the socket, gpg --card-status
        # fails with "selecting card failed: Service is not running".
        echo "  -> Enabling pcscd.socket"
        __pkg_sudo systemctl enable --now pcscd.socket \
            || __warn "could not enable pcscd.socket — enable it manually."

        # paccache.timer ships with pacman-contrib and trims the cache weekly.
        # Without it /var/cache/pacman/pkg grows without limit.
        if command -v paccache >/dev/null 2>&1; then
            echo "  -> Enabling paccache.timer"
            __pkg_sudo systemctl enable --now paccache.timer \
                || __warn "could not enable paccache.timer — enable it manually."
        fi
    fi
elif [ "$IS_HOME_INSTALL" -eq 0 ]; then
    echo "[probe] Skipping package installation."
else
    __warn "no supported package manager found — skipping packages."
fi

# -----------------------------
# Sync dotfiles via Python
# -----------------------------
echo "Syncing dotfiles to $TARGET_DIR..."
if [ "$DRY_RUN" -eq 1 ]; then
    python3 "$SCRIPT_DIR/lib/sync-dotfiles" --dry-run "$TARGET_DIR"
elif ! python3 "$SCRIPT_DIR/lib/sync-dotfiles" "$TARGET_DIR"; then
    echo "Error: sync-dotfiles failed. Aborting."
    exit 1
fi

# -----------------------------
# Remove what an earlier install left behind
# -----------------------------
# .helpers defines a `dotfiles` shell function now, and it calls bin/dotfiles.
# An alias expands before the shell looks for a function, so the alias file an
# earlier install wrote would hide the function.
ALIAS_FILE="$TARGET_DIR/.bashrc.d/dotfiles_alias"

if [ -f "$ALIAS_FILE" ]; then
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "  [dry-run] remove the old alias file $ALIAS_FILE"
    else
        echo "Removing the old dotfiles alias at '$ALIAS_FILE'."
        rm "$ALIAS_FILE"
    fi
fi

# The sync engine moved to lib/, so bin/ holds only the commands a person runs.
# An earlier install linked it into the target's bin/, where it is now a broken
# link. `dotfiles sync` replaces it.
STALE_SYNC_LINK="$TARGET_BIN_DIR/sync-dotfiles"

if [ -L "$STALE_SYNC_LINK" ] && [ "$(readlink "$STALE_SYNC_LINK")" = "$SOURCE_BIN_DIR/sync-dotfiles" ]; then
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "  [dry-run] remove the stale link $STALE_SYNC_LINK"
    else
        echo "Removing the stale sync-dotfiles link at '$STALE_SYNC_LINK'."
        rm "$STALE_SYNC_LINK"
    fi
fi

# -----------------------------
# Workspace directory
# -----------------------------
# .bash_profile exports WORKSPACE, and the fuzzy-find helpers search it. The
# directory is created here, because a login shell must not build the home
# directory as a side effect of reading its configuration.
__run mkdir -p "$TARGET_DIR/workspace"

# -----------------------------
# Sync custom scripts
# -----------------------------
echo "Syncing custom scripts to $TARGET_BIN_DIR..."

__run mkdir -p "$TARGET_BIN_DIR"
# Loop through all files in the source bin directory
for script_path in "$SOURCE_BIN_DIR"/*; do
    # Check if the glob found any files
    if [ -e "$script_path" ] && ! __skip_bin_entry "$script_path"; then
        script_name=$(basename "$script_path")
        target_path="$TARGET_BIN_DIR/$script_name"

        if [ "$DRY_RUN" -eq 1 ]; then
            echo "  [dry-run] link $script_name"
            continue
        fi

        # Make the source script executable before linking
        chmod +x "$script_path"

        echo "  -> Linking $script_name"
        # Create or update the symlink, forcing overwrite
        ln -sf "$script_path" "$target_path"
    fi
done

# -----------------------------
# Fonts (0xProto Nerd Font, vendored in general/)
# -----------------------------
if [ "$IN_CONTAINER" -eq 1 ]; then
    echo "[container] Skipping font installation (fonts render on the host)."
else
    echo "Installing 0xProto Nerd Font to $FONT_DIR..."
    __run mkdir -p "$FONT_DIR"
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "  [dry-run] copy the 0xProto TTFs into $FONT_DIR"
    else
        cp "$SCRIPT_DIR"/general/0xProto/*.ttf "$FONT_DIR/"
    fi
fi

if [ "$IS_HOME_INSTALL" -eq 1 ] && [ "$IN_CONTAINER" -eq 0 ] && [[ "$OSTYPE" != darwin* ]] && command -v fc-cache >/dev/null 2>&1; then
    __run fc-cache -f "$FONT_DIR"
fi

# -----------------------------
# Git configuration  (live state — home installs only)
# -----------------------------
if [ "$IS_HOME_INSTALL" -eq 0 ]; then
    echo "[probe] Skipping global git configuration."
elif command -v git &> /dev/null; then
    echo "Configuring global Git settings..."

    while IFS='=' read -r key value; do
        __run git config --global "$key" "$value"
    done <<< "$GIT_BASE_CONFIG"

    # No clean-gone alias: bin/git-gone does the same job as `git gone`, and it
    # prunes first, skips the current branch and takes --dry-run.

    # delta renders the diffs, but only after git is told to use it. Guard on
    # the command: the package is best-effort, and a core.pager that is not
    # installed breaks every `git diff`.
    if command -v delta >/dev/null 2>&1; then
        echo "  -> Using delta as the diff pager"
        while IFS='=' read -r key value; do
            __run git config --global "$key" "$value"
        done <<< "$GIT_DELTA_CONFIG"
    else
        echo "  -> delta not on PATH; leaving the default pager in place."
    fi

    # HTTPS remotes: keep the token in the GNOME keyring, not in a cleartext
    # ~/.git-credentials. Arch ships the helper inside git itself; other
    # distros put it elsewhere, or not at all — hence the search.
    if [[ "$OSTYPE" != darwin* ]]; then
        for helper in /usr/lib/git-core/git-credential-libsecret \
                      /usr/libexec/git-core/git-credential-libsecret; do
            if [ -x "$helper" ]; then
                echo "  -> Using $helper for HTTPS credentials"
                __run git config --global credential.helper "$helper"
                break
            fi
        done
    fi

    echo "Git configuration complete."
else
    echo "Git not found. Skipping git configuration."
fi

# -----------------------------
# GPG Agent Configuration
# -----------------------------
# agent.conf is a plain file write; the agent reload and keyring import below
# are live state (gpg reads GNUPGHOME, not GNUPG_DIR) and gated on home installs.
echo "Configuring GPG Agent..."

__run mkdir -p "$GNUPG_DIR"
__run chmod 700 "$GNUPG_DIR"

PINENTRY_PATH=""

if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS: Look for Homebrew pinentry-mac
    if command -v pinentry-mac >/dev/null; then
        PINENTRY_PATH=$(command -v pinentry-mac)
    elif [ -f "/opt/homebrew/bin/pinentry-mac" ]; then
        PINENTRY_PATH="/opt/homebrew/bin/pinentry-mac"
    elif [ -f "/usr/local/bin/pinentry-mac" ]; then
        PINENTRY_PATH="/usr/local/bin/pinentry-mac"
    else
        echo "Warning: pinentry-mac not found. Please run: brew install pinentry-mac"
    fi
else
    # Linux: prefer a GUI pinentry, then curses, then tty
    if command -v pinentry-gnome3 >/dev/null; then
        PINENTRY_PATH=$(command -v pinentry-gnome3)
    elif command -v pinentry-qt >/dev/null; then
        PINENTRY_PATH=$(command -v pinentry-qt)
    elif command -v pinentry-curses >/dev/null; then
        PINENTRY_PATH=$(command -v pinentry-curses)
    else
        # Fallback to generic link
        PINENTRY_PATH="/usr/bin/pinentry"
    fi
fi

if [ "$DRY_RUN" -eq 1 ]; then
    echo "  [dry-run] write $AGENT_CONF (pinentry: ${PINENTRY_PATH:-none found})"
else

echo "Writing gpg-agent.conf to $AGENT_CONF..."

cat <<EOF > "$AGENT_CONF"
# ---------------------------------------------------------
# GPG Agent Configuration ($AGENT_CONF_MARKER)
# ---------------------------------------------------------

# Enable SSH support so YubiKey works for SSH auth
enable-ssh-support

# Cache PIN for 1 day (86400 seconds)
default-cache-ttl 86400
max-cache-ttl 86400

# Cache SSH keys for 1 day as well
default-cache-ttl-ssh 86400
max-cache-ttl-ssh 86400

# Pinentry Program detected by install script
EOF

if [ -n "$PINENTRY_PATH" ]; then
    echo "pinentry-program $PINENTRY_PATH" >> "$AGENT_CONF"
    echo "  -> Set pinentry to $PINENTRY_PATH"
else
    echo "# WARNING: No specific pinentry-program found during install" >> "$AGENT_CONF"
    echo "  -> Warning: Could not detect pinentry program."
fi

fi  # end of the dry-run guard around the gpg-agent.conf write

if [ "$IS_HOME_INSTALL" -eq 0 ]; then
    echo "[probe] Skipping gpg-agent reload and key import."
else
    if command -v gpg-connect-agent >/dev/null; then
        echo "Reloading gpg-agent..."
        __run gpg-connect-agent reloadagent /bye
    fi

    # ---------------------------------------------------------------
    # systemd user session: make the SSH-agent handover deterministic
    # ---------------------------------------------------------------
    # .bashrc points SSH_AUTH_SOCK at gpg-agent, but that covers login shells
    # only. Graphical apps inherit the session environment instead, where:
    #   * the gpg-agent SSH socket may not be listening yet, and
    #   * GNOME starts its own SSH agent (gcr-ssh-agent, or gnome-keyring's)
    #     that claims the variable and never asks the YubiKey.
    # ~/.config/environment.d/10-gpg-ssh.conf sets the variable session-wide;
    # these two steps make sure the right agent is behind it.
    if command -v systemctl >/dev/null 2>&1 && [ -d "/run/user/$(id -u)" ]; then
        echo "  -> Enabling gpg-agent-ssh.socket"
        __run systemctl --user enable gpg-agent-ssh.socket 2>/dev/null \
            || __warn "could not enable gpg-agent-ssh.socket."
        # Starting it now fails when the agent this script reloaded a moment ago
        # already holds the socket file. The enable above is what matters —
        # systemd takes the socket at the next login.
        if [ "$DRY_RUN" -eq 0 ]; then
            systemctl --user start gpg-agent-ssh.socket >/dev/null 2>&1 || true
        fi

        for unit in gcr-ssh-agent.socket gcr-ssh-agent.service gnome-keyring-ssh.service; do
            if systemctl --user cat "$unit" >/dev/null 2>&1; then
                if [ "$DRY_RUN" -eq 1 ]; then
                    echo "  [dry-run] systemctl --user mask --now $unit"
                else
                    echo "  -> Masking $unit (GNOME's SSH agent)"
                    systemctl --user mask --now "$unit" >/dev/null 2>&1 \
                        || __warn "could not mask $unit."
                fi
            fi
        done
        echo "  -> Log out and back in for SSH_AUTH_SOCK to reach graphical apps."
    fi

    # -----------------------------
    # Import Public Key (Bootstrapping)
    # -----------------------------
    # If a public key is found in dotfiles/public.asc, this auto-imports it.
    # Command to generate: gpg --armor --export <key-id> > dotfiles/public.asc

    PUB_KEY="$DOTFILES_DIR/public.asc"
    if ! command -v gpg >/dev/null 2>&1; then
        echo "gpg not found. Skipping GPG import."
    elif [ -f "$PUB_KEY" ]; then
        echo "Importing public GPG key from $PUB_KEY..."
        __run gpg --import "$PUB_KEY"

        # This extracts the fingerprint and sets it to ultimate trust.
        FINGERPRINT=$(gpg --with-colons --import-options show-only --import "$PUB_KEY" \
            | grep -m 1 "^fpr" | awk -F: '{print $10}')

        if [ -n "$FINGERPRINT" ]; then
            echo "Setting ultimate trust for $FINGERPRINT..."
            # --import-ownertrust is the scriptable route; the interactive
            # --edit-key trust dance exits non-zero and trips set -e
            if [ "$DRY_RUN" -eq 1 ]; then
                echo "  [dry-run] set ultimate trust for $FINGERPRINT"
            else
                echo "$FINGERPRINT:6:" | gpg --import-ownertrust
            fi
        fi
    else
        echo "No public.asc found in dotfiles. Skipping GPG import."
    fi
fi

# -----------------------------
# OpenCode (terminal agent)
# -----------------------------
if [ "$IS_HOME_INSTALL" -eq 0 ] || [ "$IN_CONTAINER" -eq 1 ] || [ "$WANT_OPENCODE" -eq 0 ]; then
    echo "Skipping OpenCode installation."
elif ! command -v opencode >/dev/null 2>&1; then
    echo "Installing OpenCode..."
    case "$PKG_MGR" in
        brew)             __run brew install anomalyco/tap/opencode || __warn "OpenCode install failed." ;;
        yay|paru|pacman)  __pkg_raw "$PKG_MGR" opencode || __warn "OpenCode install failed." ;;
        *)                __run sh -c 'curl -fsSL https://opencode.ai/install | bash' || __warn "OpenCode install failed." ;;
    esac
fi

if [ "$IS_HOME_INSTALL" -eq 1 ] && [ "$IN_CONTAINER" -eq 0 ] && command -v opencode >/dev/null 2>&1; then
    echo "NOTE: run 'opencode auth login' to connect a model provider (interactive, not scripted here)."
fi

# -----------------------------
# Ghostty (terminal emulator) — best-effort
# -----------------------------
# Ghostty ships prebuilt binaries for macOS only. On Linux each distributor
# packages it: Arch and Ubuntu 26.04 carry it, Fedora has COPRs only. A machine
# without the package finds nothing, so warn and go on — the config is harmless
# without Ghostty.
if [ "$IS_HOME_INSTALL" -eq 0 ] || [ "$IN_CONTAINER" -eq 1 ] || [ "$WANT_GHOSTTY" -eq 0 ]; then
    echo "Skipping Ghostty installation."
elif ! command -v ghostty >/dev/null 2>&1; then
    echo "Installing Ghostty..."
    case "$PKG_MGR" in
        brew)             __run brew install --cask ghostty || __warn "Ghostty install failed." ;;
        yay|paru|pacman)  __pkg_raw "$PKG_MGR" ghostty || __warn "Ghostty install failed." ;;
        apt)              __pkg_raw apt ghostty \
                              || __warn "no 'ghostty' package — it needs Ubuntu 26.04 or newer. On Debian, take a .deb from github.com/mkasberg/ghostty-ubuntu." ;;
        dnf)              __pkg_raw dnf ghostty \
                              || __warn "no 'ghostty' package — enable a COPR first, for example 'dnf copr enable scottames/ghostty'." ;;
        *)                echo "No Ghostty package for this platform — install manually (skipping)." ;;
    esac
fi

# Quick-terminal opt-in: auto-enabled on macOS only; Linux needs compositor
# setup first (see dotfiles/.config/ghostty/quick-terminal.conf).
GHOSTTY_TARGET_DIR="$TARGET_DIR/.config/ghostty"
if [[ "$OSTYPE" == darwin* ]] && [ -d "$GHOSTTY_TARGET_DIR" ] && [ ! -e "$GHOSTTY_TARGET_DIR/config.local" ]; then
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "  [dry-run] write $GHOSTTY_TARGET_DIR/config.local (quick terminal)"
    else
        echo "Enabling Ghostty quick terminal (macOS)..."
        cat <<'EOF' > "$GHOSTTY_TARGET_DIR/config.local"
# Machine-local Ghostty overrides — not tracked by the dotfiles repo.
config-file = quick-terminal.conf
EOF
    fi
fi

# Hyprland reads local.conf for the monitors and the wallpaper of one machine.
# `source =` wants the file to exist, so create an empty one.
HYPR_TARGET_DIR="$TARGET_DIR/.config/hypr"
if [ "$WANT_HYPRLAND" -eq 1 ] && [ -d "$HYPR_TARGET_DIR" ] && [ ! -e "$HYPR_TARGET_DIR/local.conf" ]; then
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "  [dry-run] write $HYPR_TARGET_DIR/local.conf"
    else
        echo "Creating $HYPR_TARGET_DIR/local.conf for the machine-local Hyprland settings..."
        cat <<'EOF' > "$HYPR_TARGET_DIR/local.conf"
# Machine-local Hyprland settings — not tracked by the dotfiles repo.
# Monitors, scale, and a wallpaper go here. For example:
# monitor = , preferred, auto, 1
EOF
    fi
fi

# -----------------------------
# systemd user units (Linux)
# -----------------------------
# The Linux counterpart of a macOS LaunchAgent. lib/sync-dotfiles already
# symlinked dotfiles/.config/systemd/user/* into place; systemd still has to
# be told they exist, and units with an [Install] section get enabled.
UNIT_SRC_DIR="$DOTFILES_DIR/.config/systemd/user"

if [ "$IS_HOME_INSTALL" -eq 1 ] && [ "$IN_CONTAINER" -eq 0 ] && [ -d "$UNIT_SRC_DIR" ] \
   && command -v systemctl >/dev/null 2>&1 && [ -d "/run/user/$(id -u)" ]; then
    echo "Reloading systemd user units..."
    __run systemctl --user daemon-reload || __warn "daemon-reload failed."

    for unit_path in "$UNIT_SRC_DIR"/*.service "$UNIT_SRC_DIR"/*.timer "$UNIT_SRC_DIR"/*.socket; do
        [ -e "$unit_path" ] || continue
        grep -q '^\[Install\]' "$unit_path" || continue
        unit="$(basename "$unit_path")"
        echo "  -> Enabling $unit"
        __run systemctl --user enable --now "$unit" \
            || __warn "could not enable $unit."
    done
fi

# -----------------------------
# GNOME Shell extensions
# -----------------------------
# Ghostty's own quick terminal needs wlr-layer-shell, which Mutter does not
# implement. Quake Terminal does the same job from inside the shell: it drops
# down the Ghostty window that is already there, so one terminal config still
# covers macOS and Linux. `gnome-extensions` ships with gnome-shell, so no
# extra tooling is needed — only the right build for this shell version.
QUAKE_UUID="quake-terminal@diegodario88.github.io"

if [ "$IS_HOME_INSTALL" -eq 1 ] && [ "$IN_CONTAINER" -eq 0 ] && [ "$IS_GRAPHICAL" -eq 1 ] \
   && command -v gnome-shell >/dev/null 2>&1 && command -v gnome-extensions >/dev/null 2>&1; then
    if gnome-extensions list 2>/dev/null | grep -qx "$QUAKE_UUID"; then
        echo "Quake Terminal extension already installed."
    elif [ "$DRY_RUN" -eq 1 ]; then
        echo "  [dry-run] fetch and install the Quake Terminal extension ($QUAKE_UUID)"
    else
        echo "Installing the Quake Terminal GNOME extension..."
        SHELL_VERSION="$(gnome-shell --version | awk '{print $3}' | cut -d. -f1)"
        DOWNLOAD_PATH="$(python3 - "$QUAKE_UUID" "$SHELL_VERSION" <<'PY' || true
import json, sys, urllib.parse, urllib.request

query = urllib.parse.urlencode({"uuid": sys.argv[1], "shell_version": sys.argv[2]})
try:
    with urllib.request.urlopen(
        f"https://extensions.gnome.org/extension-info/?{query}", timeout=20
    ) as response:
        print(json.load(response)["download_url"])
except Exception:
    sys.exit(1)
PY
)"
        if [ -z "$DOWNLOAD_PATH" ]; then
            __warn "no Quake Terminal build for GNOME $SHELL_VERSION — install it from extensions.gnome.org by hand."
        else
            TMP_DIR="$(mktemp -d)"
            if curl -fsSL "https://extensions.gnome.org$DOWNLOAD_PATH" -o "$TMP_DIR/quake.zip" \
                && gnome-extensions install --force "$TMP_DIR/quake.zip"; then
                # A new extension is not loaded until the shell restarts, so
                # enabling it now fails on Wayland. It takes effect at login.
                gnome-extensions enable "$QUAKE_UUID" >/dev/null 2>&1 || true
                echo "  -> Installed. Log out and back in, then set the hotkey in its preferences."
            else
                __warn "could not install the Quake Terminal extension."
            fi
            rm -rf "$TMP_DIR"
        fi
    fi
fi

# -----------------------------
# GNOME desktop settings
# -----------------------------
# gsettings is GNOME's `defaults write`. bin/gnome-settings holds the key
# allowlist and saves the previous values, so cleanup.sh can undo this. It
# runs on any desktop with gsettings: GTK apps under Hyprland read the key
# theme and the colour scheme from the same place, and the script skips the
# schemas that only GNOME Shell installs.
if [ "$IS_HOME_INSTALL" -eq 1 ] && [ "$IN_CONTAINER" -eq 0 ] && [ "$IS_GRAPHICAL" -eq 1 ] \
   && command -v gsettings >/dev/null 2>&1; then
    echo "Applying GNOME settings..."
    __run python3 "$SOURCE_BIN_DIR/gnome-settings" apply \
        || __warn "GNOME settings failed."
fi

# -----------------------------
# Secrets git hooks
# -----------------------------
# The hook bodies live in hooks/, so a pull updates them. core.hooksPath is
# relative, so each worktree runs its own checkout.
if ! git -C "$SCRIPT_DIR" rev-parse --git-dir >/dev/null 2>&1; then
    echo "Skipping hook setup ($SCRIPT_DIR is not a git repository)."
elif [ "$DRY_RUN" -eq 1 ]; then
    echo "  [dry-run] git -C $SCRIPT_DIR config core.hooksPath hooks"
else
    echo "Pointing git hooks at hooks/ ..."
    git -C "$SCRIPT_DIR" config core.hooksPath hooks
    chmod +x "$SCRIPT_DIR/hooks/pre-commit" "$SCRIPT_DIR/hooks/pre-push" "$SCRIPT_DIR/hooks/scan-added-lines"
    # Remove the legacy copied hook: core.hooksPath makes .git/hooks dead.
    rm -f "$(git -C "$SCRIPT_DIR" rev-parse --path-format=absolute --git-common-dir)/hooks/pre-commit"
fi


# -----------------------------
# Summary
# -----------------------------
# A warning in the middle of a long package run scrolls past unread, so
# repeat them all at the end where they are the last thing on screen.
if [ "$DRY_RUN" -eq 1 ]; then
    echo
    echo "Dry run complete — nothing changed."
else
    echo "Dotfiles installation complete."
fi

if [ "$WARNING_COUNT" -gt 0 ]; then
    echo
    echo "$WARNING_COUNT step(s) need attention:"
    printf '%s' "$WARNING_LIST"
fi
